# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-meteora-intuneget

on:
  push:
    branches:
      - fix-msal-config-runtime-loading-7583242738060079211
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: acrmeteoraintuneget.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_336C22B61F0C4E07B63F21808513F2A4 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_520E7268D30543ADADEF90B9CA220DD5 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: acrmeteoraintuneget.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_336C22B61F0C4E07B63F21808513F2A4 }}/acrmeteoraintuneget/intuneget:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A505FC3FF9224FFBB61407F2667B132B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FBCBB2BF74CB4472911947AD2E6B14F5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5EE71AAAD9204AB694B4B15B892CFFAB }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-meteora-intuneget'
          slot-name: 'Production'
          images: 'acrmeteoraintuneget.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_336C22B61F0C4E07B63F21808513F2A4 }}/acrmeteoraintuneget/intuneget:${{ github.sha }}'
          